name: Route Drafts (SAFE_MODE)
on:
  workflow_dispatch:
    inputs:
      episode:
        description: "Episode ID (optional, e.g., KH-2025-08-26). If blank, process all."
        required: false
        default: ""
jobs:
  route:
    runs-on: ubuntu-latest
    env:
      SAFE_MODE: "true"
      ENABLE_X: "false"
      ENABLE_LINKEDIN: "false"
      ENABLE_INSTAGRAM: "false"
      ENABLE_YOUTUBE: "false"
      ENABLE_FACEBOOK: "false"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dev deps
        run: npm --prefix automation install
      - name: Ensure drafts exist
        run: npm --prefix automation run build:drafts || true
      - name: Route drafts (logs only)
        run: |
          if [ -n "${{ github.event.inputs.episode }}" ]; then
            npm --prefix automation run route:episode "${{ github.event.inputs.episode }}"
          else
            npm --prefix automation run route:post
          fi
